version: "3.9"

#compose stack name
name: peer-only-dev

services:
  peer:
    container_name: peer-container-dev
    image: peer-server:0.1.3-dev
    environment:
      - NODE_ENV=development
      # - PORT=3000
    build:  
      context: ./peer
      dockerfile: Dockerfile
      # Dockerfile is multistage so select only dev stage for image build
      target: dev
    volumes:
      # Define local peer directory and mount it to container's directory (at runtime) for easy data sharing between them
      - ./peer:/app
