version: "3.9"

name: peer-only

services:
  peer:
    container_name: peer-container
    image: peer-server:0.1.3
    environment:
      - NODE_ENV=production
      # - PORT=3000
    build:  
      context: ./peer
      dockerfile: Dockerfile
      # Dockerfile is multistage so select only prod stage for image build
      target: prod
    volumes:
      # Define local peer directory and mount it to container's directory (at runtime) for easy data sharing between them
      - ./peer:/app
