name: Build, Tag and Publish Peer Docker Image to Docker Hub
run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
        - 'v**-proxy'
#     branches:
#       - 'main'
#     paths:
#       - 'proxy/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # REGISTRY: docker.io
  # Might need to change this one
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_REPO: registry.com/reponame/peer
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:

  deploy-gae:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ env.GCP_SA_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        working_directory: proxy
        
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"

  build-push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code so workflow can access
        uses: actions/checkout@v3

      - name: Login to Docker Hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Tag Docker image with latest git commit
        run: docker-compose build \
              --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) \
              --no-cache
            docker tag "${{ env.IMAGE_NAME }}":latest "${DOCKERHUB_REPO}:${{ github.sha }}"

      - name: Push Docker image to registry
        run: docker push "${DOCKERHUB_REPO}:${{ github.sha }}"
