name: Build, Tag and Publish Peer Docker Image to Docker Hub
run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
        - 'peer/v**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # REGISTRY: docker.io
  # Might need to change this one
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_REPO: registry.com/reponame/peer
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:

  build-push-to-registry:
    runs-on: ubuntu-latest
    name: Publish to GHCR

    steps:

      - name: Checkout Code so Workflow can be accessed
        uses: actions/checkout@v3

      - name: Docker meta data 
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=auto
          tags: type=match,pattern=peer/v(\d.\d.\d),group=1
          images: bgunson/as-peer
      # - 
      #   name: Log in to the Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./peer
          file: ./peer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}