name: Build, Tag and Publish Peer Docker Image to Docker Hub
run-name: ${{ github.actor }} is building Peer and publishing to GHCR! 

on:
  # Triggers the workflow on push IFF pushed git tag matches pattern (i.e. peer/v4.2.0).
  push:
    tags:
        - 'peer/v**'
  # Allows workflow to be manually run from the Actions tab
  workflow_dispatch:

jobs:

  build-image-push-to-registry:
    runs-on: ubuntu-latest
    name: Publish image to GHCR

    steps:
      - name: Checkout Code so Workflow can be accessed
        uses: actions/checkout@v3
      
      - name: Install Node Modules (client)
        run: npm install
        working-directory: ./peer/frontend

      - name: Build Peer frontend
        run: npm run build
        working-directory: ./peer/frontend

      - name: Docker metadata extract
        id: meta
        uses: docker/metadata-action@v4
        with:
          # tag image as latest if peer/x.y.z tagged image pushed to registry; x,y,z are integers 
          flavor: latest=auto
          tags: type=match,pattern=peer/v(\d.\d.\d),group=1
          images: bgunson/as-peer
      
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./peer
          file: ./peer/Dockerfile
          push: true
          # Inputs to this action are provided from `Docker metadata extract` action ('meta'!)
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
