name: Proxy deploy and publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
        - 'proxy/v**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        working_directory: proxy
        
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"

  publish:
    name: Publish to GHCR
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=auto
          tags: type=match,pattern=proxy/v(\d.\d.\d),group=1
          images: ghcr.io/bgunson/as-proxy
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./proxy
          file: ./proxy/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
