name: tests

on:
  push

env:
  NODE_ENV: test
  
jobs: 
  test-peer:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - 
        name: Install peer dependencies 
        run: npm install
        working-directory: ./peer
      -
        name: Test Peer
        run: npm test
        working_directory: ./peer

  test-proxy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    -
      name: Install proxy dependencies
      run: npm install
      working-directory: ./proxy
    - 
      name: Test proxy
      run: npm test
      working-directory: ./proxy